In [1]:
import numpy as np

# 创建数组

In [3]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a = np.random.rand(3,5)
a

array([[0.2152882 , 0.37156083, 0.16506442, 0.92031815, 0.5219088 ],
       [0.24814955, 0.88652959, 0.07952279, 0.46806369, 0.15465215],
       [0.79749606, 0.57809736, 0.50081325, 0.63739579, 0.44122305]])

In [5]:
a.shape

(3, 5)

In [6]:
a.ndim

2

In [7]:
a.dtype

dtype('float64')

In [8]:
a.dtype.name

'float64'

In [9]:
a.ndim

2

In [10]:
a.itemsize

8

In [11]:
a.size

15

In [12]:
a.dtype

dtype('float64')

In [14]:
type(a)

numpy.ndarray

In [16]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [22]:
v = np.array([(6,7,8),(9,10,12)])
v

array([[ 6,  7,  8],
       [ 9, 10, 12]])

In [23]:
v.size

6

In [24]:
v.itemsize

8

In [25]:
v.ndim

2

In [26]:
a = np.zeros((3,4))
a


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
b = np.ones((3,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
c = np.empty((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:

np.arange(10,30,5).reshape(2,2)

array([[10, 15],
       [20, 25]])

In [41]:
b = np.random.rand(5,7)
a = np.ones((5,7))
a += b
a

array([[1.68130615, 1.69284706, 1.74032908, 1.19828762, 1.8602089 ,
        1.39422412, 1.86281561],
       [1.78896166, 1.11726623, 1.20473075, 1.66337951, 1.37944919,
        1.52725476, 1.32653361],
       [1.98377414, 1.05867694, 1.00079616, 1.86983787, 1.24189891,
        1.27238257, 1.44756554],
       [1.70893754, 1.34868421, 1.33193686, 1.34760295, 1.26996419,
        1.64852795, 1.31742038],
       [1.72977159, 1.39127255, 1.21873318, 1.18489189, 1.27305593,
        1.55773852, 1.92561185]])

In [42]:
np.__version__

'1.18.3'

In [45]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [49]:
np.zeros([10,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [50]:
b = np.ones([2,5])
print(f'{b.size * b.itemsize} bytes')

80 bytes


In [53]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [56]:
import pandas as pd

help pd.DataFrame

SyntaxError: invalid syntax (<ipython-input-56-d75bbc738356>, line 3)

In [57]:
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [59]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [73]:
data = np.arange(20).reshape(4,5)
print(data)
m = data[0][0]
print(m)
data[0][0] = data[3][4]
data[3][4] = m
print(data)



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
0
[[19  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18  0]]


In [74]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [75]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
arr1 = np.array([1,2,0,0,4,0])
arr1.nonzero()

(array([0, 1, 4]),)

In [94]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [96]:
np.random.rand(3,3,3)

array([[[0.0303993 , 0.29901093, 0.4233369 ],
        [0.78927973, 0.43861463, 0.51725538],
        [0.48975789, 0.81327031, 0.26754297]],

       [[0.9431276 , 0.42674286, 0.68707481],
        [0.26384361, 0.80617853, 0.30939673],
        [0.56947848, 0.579863  , 0.4512392 ]],

       [[0.72896274, 0.55934677, 0.30001558],
        [0.84936123, 0.24497213, 0.26171525],
        [0.33445373, 0.20349799, 0.04954103]]])

In [99]:
arr1 = np.random.rand(10,10)
arr1_max, arr1_min = arr1.max(), arr1.min()
arr1_max,arr1_min

(0.9539090663159547, 0.01615195818977888)

In [102]:
np.random.rand(30).mean()

0.5622896764709854

In [123]:
a = np.ones((10,8))

a[-1,-1]=0
a


array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0.]])

In [130]:
a = [1, 2, 3, 4, 5]
np.pad(a, (2, 3), 'constant',constant_values =(2,3))

array([2, 2, 1, 2, 3, 4, 5, 3, 3, 3])

In [131]:
0 * np.nan

nan

In [132]:
np.nan == np.nan

False

In [133]:
np.inf > np.nan

False

In [134]:
np.nan - np.nan

nan

In [135]:
0.3 == 3 * 0.1

False

In [136]:
0.3

0.3

In [137]:
3 * 0.1

0.30000000000000004

In [138]:
np.info(np.diag)

 diag(*args, **kwargs)

Extract a diagonal or construct a diagonal array.

See the more detailed documentation for ``numpy.diagonal`` if you use this
function to extract a diagonal and wish to write to the resulting array;
whether it returns a copy or a view depends on what version of numpy you
are using.

Parameters
----------
v : array_like
    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
    diagonal.
k : int, optional
    Diagonal in question. The default is 0. Use `k>0` for diagonals
    above the main diagonal, and `k<0` for diagonals below the main
    diagonal.

Returns
-------
out : ndarray
    The extracted diagonal or constructed diagonal array.

See Also
--------
diagonal : Return specified diagonals.
diagflat : Create a 2-D array with the flattened input as a diagonal.
trace : Sum along diagonals.
triu : Upper triangle of an array.
tril : Lower triangle of an array.

Examples
--------
>>> 

In [141]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [146]:
np.diag(1+np.arange(4),k=-2)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0]])

In [171]:
a = np.ones([8,8])
a[1::2,1::2] = 0
a[0::2,0::2] = 0
a



array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [173]:
np.info(np.unravel_index)

 unravel_index(*args, **kwargs)

unravel_index(indices, shape, order='C')

Converts a flat index or array of flat indices into a tuple
of coordinate arrays.

Parameters
----------
indices : array_like
    An integer array whose elements are indices into the flattened
    version of an array of dimensions ``shape``. Before version 1.6.0,
    this function accepted just one index value.
shape : tuple of ints
    The shape of the array to use for unraveling ``indices``.

    .. versionchanged:: 1.16.0
        Renamed from ``dims`` to ``shape``.

order : {'C', 'F'}, optional
    Determines whether the indices should be viewed as indexing in
    row-major (C-style) or column-major (Fortran-style) order.

    .. versionadded:: 1.6.0

Returns
-------
unraveled_coords : tuple of ndarray
    Each array in the tuple has the same shape as the ``indices``
    array.

See Also
--------
ravel_multi_index

Examples
--------
>>> np.unravel_index([22, 41, 37], (7,6))
(array([3, 6, 6]), array([4, 5, 1])

In [176]:
print(np.unravel_index(13,(2,8)))

(1, 5)


In [179]:
np.info(np.tile)

 tile(*args, **kwargs)

Construct an array by repeating A the number of times given by reps.

If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.

If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.

If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).

Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting operations and functions.

Parameters
----------
A : array_like
    The input array.
reps : array_like
    The number of repetitions of `A` along each axis.

Returns
-------
c : ndarray
    The tiled output array.

See Also
--------
repeat : Repeat elements of an a

In [183]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4,2))
print(Z)

[[[0 1 0 1]
  [1 0 1 0]
  [0 1 0 1]
  [1 0 1 0]
  [0 1 0 1]
  [1 0 1 0]
  [0 1 0 1]
  [1 0 1 0]]

 [[0 1 0 1]
  [1 0 1 0]
  [0 1 0 1]
  [1 0 1 0]
  [0 1 0 1]
  [1 0 1 0]
  [0 1 0 1]
  [1 0 1 0]]

 [[0 1 0 1]
  [1 0 1 0]
  [0 1 0 1]
  [1 0 1 0]
  [0 1 0 1]
  [1 0 1 0]
  [0 1 0 1]
  [1 0 1 0]]

 [[0 1 0 1]
  [1 0 1 0]
  [0 1 0 1]
  [1 0 1 0]
  [0 1 0 1]
  [1 0 1 0]
  [0 1 0 1]
  [1 0 1 0]]]


In [185]:
a = np.random.rand(5,5)
nor = (a - a.min())/(a.max()-a.min())
nor


array([[0.36389411, 0.86424004, 0.32478084, 0.87187032, 0.14624711],
       [0.32375644, 0.37485394, 0.3941508 , 0.99047949, 0.72308084],
       [0.21617055, 0.        , 0.78310341, 0.28904773, 0.97314852],
       [0.97142271, 0.61018799, 0.17141894, 0.79784108, 0.90601624],
       [0.79920673, 0.40679998, 1.        , 0.16241853, 0.14684952]])

In [189]:
color = np.dtype([("r",np.ubyte,1),
                  ("g",np.ubyte,1),
                  ("b",np.ubyte,1),
                  ('a',np.ubyte,1)])
color

/Users/shawnhua/.pyenv/versions/3.6.3/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [191]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [193]:
arr = np.arange(10)
arr[8arr > 3]

array([4, 5, 6, 7, 8, 9])

In [205]:
print(sum(range(5),-1))  


10


In [206]:

print(sum(range(5),-1))


10


In [204]:
sum(range(5),-1)

10

In [207]:
sum(range(5),-1
   
   )

10

In [211]:
z = np.arange((5))
z ** z

array([  1,   1,   4,  27, 256])

In [212]:
Z = np.arange(5)
Z <- Z   # legal

array([False, False, False, False, False])

In [213]:
Z = np.arange(5)
2j*Z   # legal

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [214]:
np.array(0) / np.array(0)

/Users/shawnhua/.pyenv/versions/3.6.3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [220]:
np.array([0,1])/np.array([0,1])



/Users/shawnhua/.pyenv/versions/3.6.3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.])

In [221]:
np.array(0) // np.array(0)  

/Users/shawnhua/.pyenv/versions/3.6.3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [228]:
np.array([np.nan]).astype(float)

array([nan])

In [236]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 2 5 7 8]


In [242]:
np.random.randint(0,10,6)

array([9, 9, 1, 9, 3, 1])

In [262]:
# Suicide mode on  
defaults = np.seterr(all="ignore")  
Z = np.ones(1) / 0  

# Back to sanity  
np.seterr(**defaults)  
Z = np.ones(1) / 0 




In [258]:
np.info(np.seterr)

 seterr(all=None, divide=None, over=None, under=None, invalid=None)

Set how floating-point errors are handled.

Note that operations on integer scalar types (such as `int16`) are
handled like floating point, and are affected by these settings.

Parameters
----------
all : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional
    Set treatment for all types of floating-point errors at once:

    - ignore: Take no action when the exception occurs.
    - warn: Print a `RuntimeWarning` (via the Python `warnings` module).
    - raise: Raise a `FloatingPointError`.
    - call: Call a function specified using the `seterrcall` function.
    - print: Print a warning directly to ``stdout``.
    - log: Record error in a Log object specified by `seterrcall`.

    The default is not to change the current behavior.
divide : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional
    Treatment for division by zero.
over : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional
  

In [268]:
np.seterr(all='warn') 
Z = np.ones(1) / 0

/Users/shawnhua/.pyenv/versions/3.6.3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


In [271]:
np.emath.sqrt(-1)

1j

In [272]:
import datetime
datetime

AttributeError: module 'datetime' has no attribute 'now'

In [274]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,)


array([3., 3., 3.])

In [291]:
np.info(np.astype)

AttributeError: module 'numpy' has no attribute 'astype'

In [298]:
np.arange(15).reshape(3,5).astype()

<function ndarray.astype>

In [287]:
np.multiply(A,B)

array([-2., -2., -2.])

In [366]:
np.floor(np.random.uniform(0,5,[4,4]))



array([[2., 4., 2., 4.],
       [1., 1., 2., 4.],
       [0., 4., 3., 2.],
       [2., 3., 1., 0.]])

In [354]:
Z = np.zeros((5,5))
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [380]:
np.info(np.linspace)

 linspace(*args, **kwargs)

Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : bool, optional
    If True, return (`samples`, `step`), where `step` is the spacing
    between samples.
dty

In [379]:

        
z = np.fromiter(np.arange(15),dtype='int')
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [389]:
np.random.uniform(2,10,2)

array([2.55124827, 4.34491326])

In [402]:
a = np.random.random(10)
a.sort()
a

array([0.00803818, 0.05405695, 0.10365802, 0.21921216, 0.51471374,
       0.73501921, 0.7598289 , 0.9172174 , 0.95195559, 0.99649045])

In [ ]:
np.array_equal(A,B)

In [406]:
np.info(np.argmax)

 argmax(*args, **kwargs)

Returns the indices of the maximum values along an axis.

Parameters
----------
a : array_like
    Input array.
axis : int, optional
    By default, the index is into the flattened array, otherwise
    along the specified axis.
out : array, optional
    If provided, the result will be inserted into this array. It should
    be of the appropriate shape and dtype.

Returns
-------
index_array : ndarray of ints
    Array of indices into the array. It has the same shape as `a.shape`
    with the dimension along `axis` removed.

See Also
--------
ndarray.argmax, argmin
amax : The maximum value along a given axis.
unravel_index : Convert a flat index into an index tuple.
take_along_axis : Apply ``np.expand_dims(index_array, axis)`` 
                  from argmax to an array as if by calling max.

Notes
-----
In case of multiple occurrences of the maximum values, the indices
corresponding to the first occurrence are returned.

Examples
--------
>>> a = np.arange(6).r

In [407]:
Z = np.random.random(10)
Z[Z.argmax()] = 0

[0.3399292  0.3820715  0.         0.6306262  0.12772328 0.52709352
 0.56994611 0.00588961 0.88941875 0.92876824]


In [409]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]
